### ISSUE TITLE
every n frames

### ISSUE THREAD

**Issue by kb0thn** [aprsworld/TimeLapse#1]
Some things we take more photos of than we want to go into the time lapse. 

We should have a use every n frames option. So if we had 1 minute images, and we wanted 10 minutes for time lapse ... we could have the time lapse assemble from every 10th photo in the camera directories.

**Comment by davarus** [comment]
Will be adding a time-span argument to select only images that occur x seconds apart.

**Comment by davarus** [comment]
Implemented in commit aa28b03ddfd82be9cc714ce16d45c131912822db.
