### ISSUE TITLE
playback rate

### ISSUE THREAD

**Issue by kb0thn** [aprsworld/TimeLapse#2]
So the time lapses seem more better to watch when I go to "faster" in VLC. And then "faster" again.

Can we specify playback speed?

**Comment by davarus** [comment]
Added a parameter in 459628ea40f0157fc29bb93f5ef5f819fde62d12 for framerate.  Was originally encoding at 24fps, now defaults to 30.  Controlling speed outside of this will be doable when Issue #1 is implemented.
